backend:
  name: github
  repo: ssigg/ako-website-metalsmith # Path to your Github repository
  branch: master # Branch to update 
media_folder: "src/assets/images"
public_folder: "/images"
collections:
- name: "index" # Used in routes, e.g. /admin/collections/blog
  label: "Start" # Used in the UI
  folder: "src/content" # The path to the folder where the documents are stored
  create: false # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Flyer", name: "flyer", widget: "image"}
    - {label: "Content", name: "body", widget: "markdown"}
- name: "archive" # Used in routes, e.g. /admin/collections/blog
  label: "Archive Entry" # Used in the UI
  folder: "src/content/archiv" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Sort Key (YYYYMM)", name: "weight", widget: "number"}
    - {label: "Flyer", name: "flyer", widget: "image"}
    - {label: "Content", name: "body", widget: "markdown"}
- name: "subscription" # Used in routes, e.g. /admin/collections/blog
  label: "Subscription" # Used in the UI
  folder: "src/content/subscription" # The path to the folder where the documents are stored
  create: false # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Program", name: "body", widget: "markdown"}