backend:
  name: github
  repo: ssigg/ako-website-metalsmith # Path to your Github repository
  branch: master # Branch to update 
media_folder: "src/assets/images"
public_folder: "/images"
display_url: https://new-ako.akademische-orchester.ch
collections:
- name: "index" # Used in routes, e.g. /admin/collections/blog
  label: "Normale Seiten" # Used in the UI
  folder: "src/content" # The path to the folder where the documents are stored
  filter: { "field": "editable", "value": true }
  create: false # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Draft", name: "draft", widget: "boolean", default: true}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Content", name: "body", widget: "markdown"}
    - {label: "Editable", name: "editable", widget: "hidden", default: true}
- name: "archive" # Used in routes, e.g. /admin/collections/blog
  label: "Archiv" # Used in the UI
  folder: "src/content/archive" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Draft", name: "draft", widget: "boolean", default: true}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Sort Key (YYYYMM)", name: "sortkey", widget: "number"}
    - {label: "Flyer", name: "flyer", widget: "image"}
    - {label: "Content", name: "body", widget: "markdown"}
    - {label: "Collection", name: "collection", widget: "hidden", default: "archive"}
- name: "subscription" # Used in routes, e.g. /admin/collections/blog
  label: "Anmeldung" # Used in the UI
  folder: "src/content/subscription" # The path to the folder where the documents are stored
  create: false # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Draft", name: "draft", widget: "boolean", default: true}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Program", name: "body", widget: "markdown"}